### PR TITLE
Add ignoreDependenciesByRegex

### LINKED ISSUE #49: Allow for group and module regex matching
Due to weirdnesses with the maven publish plugin and same module names within nested gradle middle-modules, for our internal library the group name often times has a suffix:

I.e with a module structure like this:

```
featureA:presentation
featureA:data
featureB:presentation
featureB:data
```

We publish artifacts like:

```
my.company.library.featureA:presentation
my.company.library.featureA:data
my.company.library.featureB:presentation
my.company.library.featureB:data
```

It would be great if licensee allowed a regex matching so we can specify sth like:

`ignoreDependenciesByRegex(my.company.*)`

This could work similar to gradles `exclusiveContent` matching:

```groovy
dependencyResolutionManagement {

  repositories {

    exclusiveContent {
      forRepository {
        maven {
          url 'https://maven.google.com'
        }
      }
      filter {
        includeGroupByRegex("androidx.*")
        includeGroupByRegex("com.android.tools.build.*")
        includeGroupByRegex("com.android.*")
        includeGroup("com.google.firebase")
```

### PR DESCRIPTION
**Pull request by consp1racy**
Fixes https://github.com/cashapp/licensee/issues/49.

### What's done
* Implement the thing.
* Fix running tests on Windows by checking golden text files with LF line endings. `violationsIgnored[...]` and `violationsLogged[...]` remain unfixed.
* `installArchives` publishes files under `${projectDir}/build` where tests expect them, instead of `buildDir` which, in my case, resides decoupled on a RAM disk.

### CODE REVIEW

**Comment by consp1racy** [comment]
Any idea how to prevent jitpack from trying to include test maven repos?

https://jitpack.io/com/github/consp1racy/licensee/ep~regex-ignore-1.4.0-gd38f8aa-5/build.log

**Comment by JakeWharton** [comment]
Thanks for the PR. I'll review it next week.

**Comment by ybentlili** [comment]
Hello @JakeWharton  any update about this PR ? As I see, it is not yet merged ..

**Comment by SmialyKot** [comment]
Any update on this feature?

**Comment by consp1racy** [comment]
I'll have to split it into three separate PRs as outlined above. Then I'll have to resolve the conflicts

**Comment by consp1racy** [comment]
Gradle 8.1 has this for repository content descriptors, which would fit my needs.
```
/**
     * Declares that an entire group and its subgroups should be searched for in this repository.
     *
     * <p>
     * A subgroup is a group that starts with the given prefix and has a dot immediately after the prefix.
     * For example, if the prefix is {@code org.gradle}, then {@code org.gradle} is matched as a group,
     * and {@code org.gradle.foo} and {@code org.gradle.foo.bar} are matched as subgroups. {@code org.gradlefoo}
     * is not matched as a subgroup.
     * </p>
     *
     * @param groupPrefix the group prefix to include
     * @since 8.1
     */
    @Incubating
    void includeGroupAndSubgroups(String groupPrefix);
```
This would be easier than regex.

**Pull request closed without merging**
