### PR TITLE
Fix maven builder

### LINKED ISSUE #180: License check fails with 1.7.0
Hi people,

Our project license check fails if we use 1.7 plugin version and pass with 1.6:

```
> Error while evaluating property 'coordinatesToPomInfo' of task ':project:licenseeDebug'.
   > Failed to calculate the value of task ':project:licenseeDebug' property 'coordinatesToPomInfo'.
      > 1 problem was encountered while building the effective model for com.google.code.gson:gson:2.8.9
        [ERROR] Failed to determine Java version for profile doclint-java8-disable @ com.google.code.gson:gson-parent:2.8.9
```

### PR DESCRIPTION
**Pull request by hfhbd**
Fixes #180

I have no idea why this fixes the pom...

### CODE REVIEW

**Review by JakeWharton — APPROVED** [review]

**Comment by JakeWharton** [comment]
Thanks for following up on it

**Comment by hfhbd** [comment]
I just want to see 1.7.0 :P

**Comment by JakeWharton** [comment]
I'm off paternity leave in 4 weeks. I'll test on our work codebase and release then.

**Comment by hfhbd** [comment]
Sorry, no stress, enjoy the time. It's open source and forking is easy. You even do snapshots so it's all fine.

**Pull request merged**
